kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backend-pv-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
