kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/jenkins"

