master:
  installPlugins:
    - kubernetes:1.15.5
    - workflow-aggregator:2.6
    - workflow-job:2.32
    - git:3.10.0
    - github:1.29.4
    - github-branch-source:2.5.3
  slaveKubernetesNamespace:
    kube-system
  servicePort: 80
agent:
  enabled: true
persistence:
  enabled: true
  existingClaim: jenkins-pv-claim

